import type { SeverityLevel } from "../api/gad"

export interface Respondent {
  name: string
  age: number
}

export const GAD7_ITEMS: Record<Languages, string[]> = {
  en: [
    "Feeling nervous, anxious, or on edge",
    "Not being able to stop or control worrying",
    "Worrying too much about different things",
    "Trouble relaxing",
    "Being so restless that it is hard to sit still",
    "Becoming easily annoyed or irritable",
    "Feeling afraid, as if something awful might happen",
  ],
  id: [
    "Merasa gugup, cemas, atau tegang",
    "Tidak dapat menghentikan atau mengendalikan rasa khawatir",
    "Terlalu khawatir tentang berbagai hal",
    "Sulit untuk merasa santai",
    "Merasa sangat gelisah sehingga sulit untuk duduk diam",
    "Menjadi mudah kesal atau tersinggung",
    "Merasa takut seolah-olah sesuatu yang buruk akan terjadi",
  ],
}

export const RESPONSE_LABELS: Record<Languages, string[]> = {
  en: [
    "Not at all",
    "Several days",
    "More than half the days",
    "Nearly every day",
  ],
  id: [
    "Tidak pernah",
    "Beberapa hari",
    "Lebih dari separuh waktu",
    "Hampir setiap hari",
  ],
}

export const SEVERITY_BANDS: { key: SeverityLevel; width: number }[] = [
  { key: "Minimal", width: 5 / 21 },
  { key: "Mild", width: 5 / 21 },
  { key: "Moderate", width: 5 / 21 },
  { key: "Severe", width: 6 / 21 },
]

export const SEVERITY_LABELS: Record<
  Languages,
  Record<SeverityLevel, string>
> = {
  en: {
    Minimal: "Minimal",
    Mild: "Mild",
    Moderate: "Moderate",
    Severe: "Severe",
  },
  id: {
    Minimal: "Minimal",
    Mild: "Ringan",
    Moderate: "Sedang",
    Severe: "Berat",
  },
}

export const SEVERITY_INTERPRETATION: Record<
  Languages,
  Record<SeverityLevel, string>
> = {
  en: {
    Minimal:
      "Scores in this range suggest minimal anxiety symptoms. Continue to monitor how you're feeling and revisit the screening if things change.",
    Mild: "Scores in this range suggest mild anxiety symptoms. These may come and go, but it's worth keeping an eye on how they affect daily life.",
    Moderate:
      "Scores in this range suggest anxiety symptoms that may be affecting daily functioning. Consider speaking with a mental health professional for a full evaluation.",
    Severe:
      "Scores in this range suggest significant anxiety symptoms. It's strongly recommended to consult a mental health professional as soon as possible.",
  },
  id: {
    Minimal:
      "Skor pada rentang ini menunjukkan gejala kecemasan yang minimal. Tetap pantau perasaan Anda dan lakukan skrining ulang jika ada perubahan.",
    Mild: "Skor pada rentang ini menunjukkan gejala kecemasan ringan. Gejala ini bisa hilang timbul, namun tetap perlu diperhatikan pengaruhnya terhadap aktivitas sehari-hari.",
    Moderate:
      "Skor pada rentang ini menunjukkan gejala kecemasan yang dapat memengaruhi aktivitas sehari-hari. Disarankan untuk berkonsultasi dengan tenaga profesional kesehatan mental untuk evaluasi lebih lanjut.",
    Severe:
      "Skor pada rentang ini menunjukkan gejala kecemasan yang signifikan. Sangat disarankan untuk segera berkonsultasi dengan tenaga profesional kesehatan mental.",
  },
}

export const UI_TEXT: Record<
  Languages,
  {
    appName: string
    title: string
    resultId: string
    name: string
    age: string
    consent: string
    consentConfirmed: string
    totalScore: string
    ruleBased: string
    mlPredicted: string
    confidence: string
    agree: string
    disagree: string
    gaugeCaption: string
    whatThisMeans: string
    itemBreakdown: string
    itemNumber: string
    itemSymptom: string
    itemResponse: string
    disclaimer: string
    consentModalTitle: string
    consentModalSubtitle: string
    namePlaceholder: string
    agePlaceholder: string
    consentCheckboxText: string
    cancelButton: string
    generateButton: string
    saveButton: string
    generatingButton: string
  }
> = {
  en: {
    appName: "CarePoint",
    title: "GAD-7 screening result",
    resultId: "Result ID",
    name: "Name",
    age: "Age",
    consent: "Consent",
    consentConfirmed: "Confirmed",
    totalScore: "Total score",
    ruleBased: "Rule-based",
    mlPredicted: "ML-predicted",
    confidence: "Confidence",
    agree: "Both methods agree",
    disagree: "Methods differ — boundary case",
    gaugeCaption: "Severity scale",
    whatThisMeans: "What this means",
    itemBreakdown: "Item breakdown",
    itemNumber: "#",
    itemSymptom: "Symptom in past 2 weeks",
    itemResponse: "Response",
    disclaimer:
      "This is an automated screening result, not a clinical diagnosis. Generated by CarePoint.",
    consentModalTitle: "Before you download",
    consentModalSubtitle: "These details appear on your result document.",
    namePlaceholder: "Your full name",
    agePlaceholder: "Your age",
    consentCheckboxText:
      "I confirm I will not use this screening result for any malicious act, and understand it is not a clinical diagnosis.",
    cancelButton: "Cancel",
    generateButton: "Generate PDF",
    saveButton: "Save result as PDF",
    generatingButton: "Generating PDF...",
  },
  id: {
    appName: "CarePoint",
    title: "Hasil skrining GAD-7",
    resultId: "ID Hasil",
    name: "Nama",
    age: "Usia",
    consent: "Persetujuan",
    consentConfirmed: "Dikonfirmasi",
    totalScore: "Skor total",
    ruleBased: "Berbasis aturan",
    mlPredicted: "Prediksi ML",
    confidence: "Tingkat keyakinan",
    agree: "Kedua metode sepakat",
    disagree: "Metode berbeda — kasus batas",
    gaugeCaption: "Skala tingkat keparahan",
    whatThisMeans: "Apa artinya ini",
    itemBreakdown: "Rincian per item",
    itemNumber: "#",
    itemSymptom: "Gejala dalam 2 minggu terakhir",
    itemResponse: "Jawaban",
    disclaimer:
      "Ini adalah hasil skrining otomatis, bukan diagnosis klinis. Dibuat oleh CarePoint.",
    consentModalTitle: "Sebelum mengunduh",
    consentModalSubtitle:
      "Detail ini akan ditampilkan pada dokumen hasil Anda.",
    namePlaceholder: "Nama lengkap Anda",
    agePlaceholder: "Usia Anda",
    consentCheckboxText:
      "Saya menyatakan tidak akan menggunakan hasil skrining ini untuk tindakan yang merugikan, dan memahami bahwa ini bukan diagnosis klinis.",
    cancelButton: "Batal",
    generateButton: "Buat PDF",
    saveButton: "Simpan hasil sebagai PDF",
    generatingButton: "Membuat PDF...",
  },
}

export function scorePosition(score: number): number {
  const clamped = Math.max(0, Math.min(21, score))
  return clamped / 21
}
